name: Testing CI
on: [push, pull_request]
jobs:
  execute-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Test with unittest
        run: |
          pip install coverage
          coverage run --source=./TaskInterface -m unittest discover -p="Test*.py"
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  
  linting:
    needs: execute-tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff check --output-format=github
      
  type-check:
    needs: execute-tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install mypy
      - name: Run mypy
        run: mypy --disallow-untyped-defs .