name: Testing CI
on: [push]
jobs:
  test-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"